### PR TITLE
Fix bug in variadic function argument count

### LINKED ISSUE #210: Variadic functions don't seem to work
Hi,

Using libffi 3.2.1, Perl 5.28, FFI::Platypus 1.06, on Linux. Trying out the two examples for variadic functions in the documentation
```perl
use warnings;
use strict;
use FFI::Platypus;
my $ffi = FFI::Platypus->new( api => 1 );
$ffi->lib(undef);
$ffi->function( printf => ['string'] => ['int'] => 'int' )
    ->call("print integer %d\n", 42);
$ffi->function( printf => ['string'] => ['string'] => 'int' )
    ->call("print string %s\n", 'platypus');
```
gives random integers and random junk strings as output, different on each run, e.g.
```
print integer -254260256
print string �
```
Any help is appreciated!

### PR DESCRIPTION
**Pull request by plicease**
The argument name for `ffi_prep_cif_var` was named to something that sounded like it was just the variable arguments, but according to the documentation is actually a count of alllll of the arguments.  The tests that I wrote just happen to work with the wrong input (at least on x86).  This adjusts the tests to be more aggressive, including some tests that are similar to the examples that we site in the documentation (which I apparently never tested).  This should fix #210.

### CODE REVIEW

File: t/ffi/variadic.c [hunk 1]
```diff
@@ -2,22 +2,72 @@
 #ifdef FFI_PL_PROBE_VARIADIC
 #include <stdio.h>
 #include <stdarg.h>
+#include "libtest.h"
 
-int
+EXTERN int
```
Comment (plicease) [inline t/ffi/variadic.c]: This also fixes a bug where the variadic functions weren't being tested on Visual C++ because the tester functions for it weren't being exported from the DLL :/
